dist: trusty
language: java
jdk:
  - oraclejdk8
script: mvn clean test
script: find . -name "*.jar"
#before_install: cd ProtocolLib
install: true

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GH_TOKEN
  file_glob: true
  file:
    - "ProtocolLib*/modules/ProtocolLib/target/*.jar"
  on:
    tags: true
