dist: trusty
language: java
jdk:
  - oraclejdk8
script: mvn install && find . -name "*.jar" &&  ls modules/ProtocolLib/target/
#before_install: cd ProtocolLib
install: true

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GH_TOKEN
  file_glob: true
  file:
    - "modules/ProtocolLib/target/*.jar"
  on:
    tags: true
